### ISSUE TITLE
Need to generate a Default.toml project first   

### ISSUE THREAD

**Issue by abhinav-adhikari** [varnerlab/JuCFMG#2]
**make_julia_model** function does not work unless _**Default.toml**_ is present in the test folder. 

Generate an informative error message.

**Comment by varnerlab** [comment]
We check for the existence of the Defaults.toml file. If not there, we throw and error:
 throw(ArgumentError("Ooops! We are missing the Defaults.toml file. Please generate a default project using the generate_default_project function. For details see the generate_default_project help in the REPL"))

Checked in: 647a9803e0f532be8e1be97e22651df24009b6e5

**Comment by varnerlab** [comment]
We added a section to the README.m telling the user to first generate a default project structure. See: https://github.com/varnerlab/JuCFMG/commit/e77c1be6106944fa8da1e0c959f59de9404b298e

**Comment by varnerlab** [comment]
Closed
